name: CI
on:
  push:
    paths:
      - '**.py'
      - '**.cfg'
      - 'requirements.txt'
  pull_request:
    paths:
      - '**.py'
      - '**.cfg'
      - 'requirements.txt'
jobs:
  test:
    strategy:
      matrix:
        runner: [ ubuntu-latest, macos-latest ]
        python: [ "3.8", "3.9", "3.10" ]
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install -r requirements.txt

      - name: Run tox
        run: tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
